#!/usr/bin/env bash
# Runs Nginx as the www-data user

sudo sed -i "s/#user www-data/user www-data/" /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sudo chown www-data:www-data /etc/nginx/nginx.conf
sudo sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
sudo service nginx restart
